# Generated by Django 5.1.3 on 2024-11-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='patient',
        ),
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('problem_description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания продукта')),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_patient2', to='task.patient')),
            ],
            options={
                'verbose_name': 'Годовое сопровождение',
                'verbose_name_plural': 'Марафон похудения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_patient', to='task.patient'),
        ),
    ]
